### ISSUE TITLE
[Bugtorch] Crash when trying to launch pack with BugTorch-1.1.1-GTNH

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#8255]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
Update Bugtorch from 1.0.4 to 1.1.1 from jenkins, launch the pack
#
#### What happened instead? (Attach screenshots if needed)
Crash during launch phase involving Openblocks (apparently?)
`[09:50:20] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NoClassDefFoundError: openblocks/asm/OpenBlocksClassTransformer$1`
Full log:
https://pastebin.com/sQja8udk

Using hodgepodge-1.7.10-1.6.8 and SpongeMixins-1.3.2 and OpenBlocks-1.7.10-1.6.3-1.7.10-snapshot-6
#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
Afx237v7

**Comment by jss2a98aj** [comment]
The link to the full log is giving a 404. I am not encountering any crashes while using a fresh install of GTNH with BugTorch 1.1.1-GTNH. Please re-upload the log.

**Comment by GTNH-Afx237v7** [comment]
[fml-client-3.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6842821/fml-client-3.log)

See attached full log, no idea why the pastebin.com link went 404....

**Comment by GTNH-Afx237v7** [comment]
So I tried again and the same error appeared.

However it will load just fine if `fixShearedBlocksDropExtraItems` is set to `false` in the mixins.cfg config file.

**Comment by GTNH-Afx237v7** [comment]
Had the same issue happen today after updating to 2.1.1.1.a. Same fix, disable above mentioned config option.
Could it be that GraalVM is the cause, as I have been using this instead of „plain“ java?

**Comment by Glease** [comment]
Try this jar: http://jenkins.usrv.eu:8080/job/BugTorch/13/artifact/build/libs/BugTorch-1.1.2-GTNH.jar

Might have forget to update it.

**Comment by GTNH-Afx237v7** [comment]
So after some trial and error I was able to track it down to the JVM argument `-noverify` that I have added in my settings. Deleting this argument will launch fine.

**Comment by Glease** [comment]
So issue resolved. Closing for now.
