### ISSUE TITLE
GTNH Pack Near to Compatible With Fisk's Superheroes Mod( just little help)

### ISSUE THREAD

**Issue by LightVoldigoad** [GTNewHorizons/GT-New-Horizons-Modpack#25555]
### Your GTNH Discord Username

PowerMink7377

### Your Pack Version

2.8.4

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

## Compatibility Report: Fisk's Superheroes 2.4.0 on GTNH 2.8.4

I spent a significant amount of time attempting to get Fisk's Superheroes (FiskHeroes-1.7.10-2.4.0.jar) working with GT New Horizons 2.8.4. Here is a detailed summary of what was tried and where we got stuck, in hopes that someone can take it further.

---

### Step 1 — Initial Crash (Pre-Initialization)

Adding Fisk's Superheroes directly to GTNH caused the game to freeze during Pre-Initialization and never reach the main menu. The crash report revealed:

```
java.lang.NoClassDefFoundError: mods/battlegear2/api/RenderPlayerEventChild$PreRenderSheathed
    at com.fiskmods.heroes.common.proxy.ClientProxy.preInit(ClientProxy.java:123)
```

Fisk's Superheroes tries to register a BattleGear 2 event handler during pre-init. It specifically looks for `RenderPlayerEventChild$PreRenderSheathed`, which exists in vanilla BattleGear 2 but is **absent in GTNH's custom fork** (`battlegear2-1.5.9-backhand.jar`), which was stripped down to work with the Backhand mod.

---

### Step 2 — Injecting Missing Classes

To fix this, we extracted all API classes from the vanilla BattleGear 2 JAR (`1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar`) and injected them into GTNH's `battlegear2-1.5.9-backhand.jar` using zip/jar tools.

This included:
- `mods/battlegear2/api/RenderPlayerEventChild$PreRenderSheathed.class`
- `mods/battlegear2/api/RenderPlayerEventChild$PostRenderSheathed.class`
- `mods/battlegear2/api/core/InventoryPlayerBattle.class`
- And all other vanilla API classes

**Result:** The game successfully loaded! All 312 mods initialized without errors. Fisk's Superheroes appeared in the mod list and the main menu was reachable.

---

### Step 3 — In-Game Crash (Render Stage)

After loading into a world, the game crashed as soon as rendering began (even without equipping a suit). The crash report:

```
java.lang.NoSuchMethodError: mods.battlegear2.api.core.IOffhandRender.battlegear2$getOffHandItemToRender()Lnet/minecraft/item/ItemStack;
    at mods.battlegear2.client.utils.BattlegearRenderHelper.renderItemInFirstPerson(BattlegearRenderHelper.java:70)
    at com.fiskmods.heroes.client.render.entity.SHEntityRenderer.updateCameraAndRender(SHEntityRenderer.java:62)
```

---

### Root Cause

This is where we hit a wall. The method `battlegear2$getOffHandItemToRender()` on `IOffhandRender` is **not a standard Java method** — it is dynamically injected at runtime by GTNH's Backhand mod using the **Mixin system**. This means:

- The method does not exist in any `.class` file that can be extracted or injected manually.
- Fisk's Superheroes calls this method through BattleGear 2's render helper, expecting it to be present on any object implementing `IOffhandRender`.
- Since Fisk implements `IOffhandRender` for its suit rendering, the Backhand mixin's injected method is expected — but Fisk was never written to be compatible with Backhand's specific mixin-based API extensions.

### What Would Be Needed to Fix This

A proper fix would require one of the following:

1. **Fisk's Superheroes source code modification** — The render integration with BattleGear 2 in `ClientProxy` and related render classes would need to be updated to handle the Backhand-specific API (or gracefully skip it when Backhand is present instead of vanilla BattleGear 2).

2. **A compatibility layer** — A small compat mod or mixin that bridges Fisk's expectations with Backhand's runtime-injected API.

---

### Environment
- GTNH Version: 2.8.4
- Fisk's Superheroes: 2.4.0 (1.7.10)
- Java: OpenJDK 1.8.0_312
- Launcher: CurseForge

Hope this helps anyone who wants to take a crack at a real fix!

### Crash Report

---- Minecraft Crash Report ----
Time: 2026-06-27 14:43:02 TRT
Description: Unexpected error

java.lang.NoSuchMethodError: mods.battlegear2.api.core.IOffhandRender.battlegear2$getOffHandItemToRender()Lnet/minecraft/item/ItemStack;
    at mods.battlegear2.client.utils.BattlegearRenderHelper.renderItemInFirstPerson(BattlegearRenderHelper.java:70)
    at net.minecraft.client.renderer.ItemRenderer.handler$zne001$battlegear2$renderItemInFirstPerson(ItemRenderer.java:3832)
    at net.minecraft.client.renderer.ItemRenderer.renderItemInFirstPerson(ItemRenderer.java:542)
    at net.minecraft.client.renderer.EntityRenderer.mixinextras$bridge$func_78440_a$83(EntityRenderer.java)
    at net.minecraft.client.renderer.EntityRenderer.wrapOperation$zeb000$angelica$iris$disableVanillaRenderHand(EntityRenderer.java:4114)
    at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:736)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1361)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1011)
    at com.fiskmods.heroes.client.render.entity.SHEntityRenderer.updateCameraAndRender(SHEntityRenderer.java:62)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.run(Minecraft.java:7610)

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by PLASMAchicken** [comment]
Is Fisk's Superheroes source code available and open source? Then I can fix it. Otherwise no

**Comment by PLASMAchicken** [comment]
Ask the Fisk, the mod is All Rights Reserved.

**Comment by fbfnysnshnsgnwg** [comment]
Don't use AI to write your issue for you
