### ISSUE TITLE
last master version's bartworks crash the game

### ISSUE THREAD

**Issue by bjin2000** [GTNewHorizons/GT-New-Horizons-Modpack#10151]
### Your GTNH Discord Username

mini_ben#0027

### Your Pack Version

2.1.2.3qf with newest bartworks

### Your Server

SP

### Your Actions

update bartworks to the newest one in jenkins

### Crash Report

I can load the existing world without error. If I create a new world, the game will crash with fluid corruption.

[crash-2022-04-14_00.40.21-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8486305/crash-2022-04-14_00.40.21-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by LewisSaber** [comment]
Did u download latest master branch build or other branch build

**Comment by GTNHAfx237v7** [comment]
Title says master version? So I’d assume it’s master branch. I had the same issue a few weeks ago, had to resort to the version of bartworks that came with 2.1.2.3QF.

**Comment by LewisSaber** [comment]
im blind ig
try updating gregtech as well maybe?

**Comment by bjin2000** [comment]
In fact, I have updated all mods to the newest one. Same as GTNHAfx237v7, the version of bartworks in 2.1.2.3qf works perfectly.

**Comment by Dream-Master** [comment]
@bjin2000 why you not waiting of a new version. Try unfinished or uncompatible stuff fill up the issue list with stuff been fixed later on.
If you test a dev version which are not out yet you can report bugs but add ranom newer mod version is not relay helpful.
btw my dev pack has newest bartworks and work well.
Do me a favor and wait for a 2.1.2.4 dev version. Thanks

**Comment by Dream-Master** [comment]
@GTNHAfx237v7 
@LewisSaber

**Comment by bjin2000** [comment]
@Dream-Master Sorry for the extra work. Since a few mods in the 2.1.2.3qf package need to be updated, I tried updating them all to try out the latest features. I only found those two mods will cause the game to crash. Therefore, I want to give some notice to the developers. If the mod works well in the dev package, that's the best result.
In addition, I want to notice that the last version of the hodgepodge(#115 bop fixes) in jenkins may have a compile issue. (java.lang.NoClassDefFoundError: biomesoplenty/common/integration/ForestryIntegration). The #110 version works fine.
Sorry again for the additional work.

**Comment by Dream-Master** [comment]
@glowredman what means the forestry issue ?

**Comment by glowredman** [comment]
@bjin2000 use the latest version of BoP for 1.7.10 from Curseforge

**Comment by bjin2000** [comment]
@glowredman @Dream-Master Thank you for the wonderful discussion. Now, I figure out what went wrong with BoP fixes. The GTNewHorizons package uses the custom BoP from [BiomesOPlenty-1.7.10-2.1.3-GTNH.jar](http://downloads.gtnewhorizons.com/Mods_for_Twitch/BiomesOPlenty-1.7.10-2.1.3-GTNH.jar), but the hodgepodge compiles with "curse.maven:biomes-o-plenty-220318:2499612".

**Comment by Glease** [comment]
Which is why we tell you use the curse version of biomes o plenty.
