### ISSUE TITLE
AE Autocrafing broken in 2.2.9

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#12570]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.2.9 (java19). this uses appliedenergistics2-rv3-beta-156-GTNH

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Easy steps to reproduce:
1. pattern gold dust - > gold ingots
2. pattern gold ingots- > gold plates
3. zero ingots and plates but plenty dust

then order gold plates.

result: gold ingots are crafted but the recipe gets stuck and the gold ingots just go to storage.

this also happens for any other recipe combo, this is just a simple example to reproduce.

(got a confirmation by gdc though he didnt follow these steps exactly)

### The Reality

see above. so single recipes work, but no chains. Supposedly things worked fine on 2.2.9 9-dev-pre with appliedenergistics2-rv3-beta-154-GTNH

### Your Proposal

fix it!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
this are the changes
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/compare/rv3-beta-154-GTNH...rv3-beta-156-GTNH

@eigenraven @asdflj any idea ?

**Comment by chochem** [comment]
reverting to 155 fixed everything. So it is caused by https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/240

**Comment by hucking** [comment]
not sure if this is related or not but when opening interface terminal and when requesting fluid crafting we had server crashes, adding crash reports here:
this was the first one when opening interface terminal:
```
java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP
	at appeng.container.implementations.ContainerInterfaceTerminal.func_75142_b(ContainerInterfaceTerminal.java:95)
	at net.minecraft.inventory.Container.func_75132_a(SourceFile:54)
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88)
	at net.minecraft.entity.player.EntityPlayer.openGui(Unknown Source)
	at appeng.util.Platform.openGUI(Platform.java:320)
	at appeng.parts.reporting.PartInterfaceTerminal.onPartActivate(PartInterfaceTerminal.java:39)
	at appeng.parts.AEBasePart.onActivate(AEBasePart.java:430)
	at appeng.parts.CableBusContainer.activate(CableBusContainer.java:641)
	at appeng.block.networking.BlockCableBus.onActivated(BlockCableBus.java:397)
	at appeng.block.AEBaseTileBlock.func_149727_a(AEBaseTileBlock.java:288)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityClientPlayerMP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:114)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 21 more

```
and this was second after requesting fluid crafting (which also caused crash on startup because it kept trying to craft the fluid): 
```
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP
	at appeng.helpers.DualityInterface.isBusy(DualityInterface.java:867)
	at appeng.me.cluster.implementations.CraftingCPUCluster.executeCrafting(CraftingCPUCluster.java:561)
	at appeng.me.cluster.implementations.CraftingCPUCluster.updateCraftingLogic(CraftingCPUCluster.java:528)
	at appeng.me.cache.CraftingGridCache.onUpdateTick(CraftingGridCache.java:128)
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:30)
	at appeng.me.Grid.update(Grid.java:248)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:189)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_773_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityClientPlayerMP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:114)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 14 more

```

**Comment by chochem** [comment]
@hucking you should go one thread over <https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12569>

**Comment by asdflj** [comment]
it's look like ae2fc asm broken

**Comment by asdflj** [comment]
fixed https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/242

**Comment by asdflj** [comment]
![image](https://user-images.githubusercontent.com/33802162/218629081-e564d769-9393-4345-aad2-7ee784956e57.png)

**Comment by asdflj** [comment]
i tried to using fixed version it's look like fine and working
running in 2.2.9

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/releases/tag/rv3-beta-157-GTNH-pre

**Comment by chochem** [comment]
doesnt work

**Comment by Dream-Master** [comment]
@asdflj

**Comment by k3nw4y** [comment]
> Easy steps to reproduce:
> 
> 1. pattern gold dust - > gold ingots
> 2. pattern gold ingots- > gold plates
> 3. zero ingots and plates but plenty dust
> 
> then order gold plates.
> 
> result: gold ingots are crafted but the recipe gets stuck and the gold ingots just go to storage.
> 
> this also happens for any other recipe combo, this is just a simple example to reproduce.

i can reproduce the issue by following the steps
![image](https://user-images.githubusercontent.com/46229190/218780110-89878fda-4e7b-4e17-a82b-d03edf847e3b.png)
![image](https://user-images.githubusercontent.com/46229190/218780203-175d2e52-8823-4a54-bd57-66cb6560082d.png)

**Comment by k3nw4y** [comment]
seems like it works fine with full block interface, not the non full block version

**Comment by asdflj** [comment]
i fixed in new version

**Comment by asdflj** [comment]
![image](https://user-images.githubusercontent.com/33802162/218782162-6324f747-0028-4ee2-b6bd-719772dc188d.png)

**Comment by asdflj** [comment]
can we to talk in the dc?

**Comment by k3nw4y** [comment]
yeah im in there k3nw4_y#7664

**Comment by chochem** [comment]
fixed in 2.2.10 pre1
